In [8]:
import matplotlib.image as img
import numpy as np
import pandas as pd 
import tensorflow as tf
import matplotlib.pyplot as plt

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.preprocessing.image import ImageDataGenerator

from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from scipy import stats

df = pd.read_csv('./data/deepfake_ex/metadata.csv')

df_real = df.loc[df['label']=='REAL']
df_fake = df.loc[df['label']=='FAKE']

display(df_real)
display(df_fake)
display(df.loc[df['videoname']=='aaagqkcdis.mp4'])

list_df_real = []
list_df_fake = []
tmp = ''

for i in df_real['videoname']:
    tmp = i[0:-3]+'jpg'
    list_df_real.append(tmp)
for i in df_fake['videoname']:
    tmp = i[0:-3]+'jpg'
    list_df_fake.append(tmp)

print(len(list_df_real))
print(len(list_df_fake))

            videoname  original_width  original_height label original
17     mcehvkoidm.mp4             186              185  REAL      NaN
26     wzrybcopcd.mp4             223              223  REAL      NaN
30     tvrwjmjeyn.mp4             107              107  REAL      NaN
47     gnrbhysdok.mp4             186              186  REAL      NaN
68     gzmsocbmkz.mp4             107              107  REAL      NaN
...               ...             ...              ...   ...      ...
95614  dfaslvpqyj.mp4              89               90  REAL      NaN
95618  bxsdnqizii.mp4             107              108  REAL      NaN
95620  eqoknwfyci.mp4             129              129  REAL      NaN
95622  aiovoszqsn.mp4              89               89  REAL      NaN
95624  afgvjnqstv.mp4             185              185  REAL      NaN

[16293 rows x 5 columns]

            videoname  original_width  original_height label        original
0      aznyksihgl.mp4             129              129  FAKE  xnojggkrxt.mp4
1      gkwmalrvcj.mp4             129              129  FAKE  hqqmtxvbjj.mp4
2      lxnqzocgaq.mp4             223              217  FAKE  xjzkfqddyk.mp4
3      itsbtrrelv.mp4             186              186  FAKE  kqvepwqxfe.mp4
4      ddvgrczjno.mp4             155              155  FAKE  pluadmqqta.mp4
...               ...             ...              ...   ...             ...
95629  rqcsjlsmiz.mp4             129              129  FAKE  pbsccacgff.mp4
95630  xjmnerypjf.mp4              90               90  FAKE  qrjydgidga.mp4
95631  hnewpzhihy.mp4              75               75  FAKE  vabhbfiifl.mp4
95632  okbarlnmwm.mp4             268              267  FAKE  uqaaspbgtz.mp4
95633  asddammewq.mp4              90               90  FAKE  yfjkgiynbi.mp4

[79341 rows x 5 columns]

            videoname  original_width  original_height label        original
18722  aaagqkcdis.mp4              90               89  FAKE  eklsrnkwog.mp4

16293
79341

In [9]:
# 폴더구조 생성 및 real, fake 이미지 각 폴더로 복사
# 작은버전
import os, shutil

original_dataset_dir = './data/deepfake_ex/sample224'

base_dir = 'data/deepfake_ex/dataset'
os.mkdir(base_dir)

train_dir = os.path.join(base_dir,'train')
os.mkdir(train_dir)
validation_dir = os.path.join(base_dir,'validation')
os.mkdir(validation_dir)
test_dir = os.path.join(base_dir,'test')
os.mkdir(test_dir)


train_cats_dir = os.path.join(train_dir,'real')
os.mkdir(train_cats_dir)
train_dogs_dir = os.path.join(train_dir,'fake')
os.mkdir(train_dogs_dir)

validation_cats_dir = os.path.join(validation_dir,'real')
os.mkdir(validation_cats_dir)
validation_dogs_dir = os.path.join(validation_dir,'fake')
os.mkdir(validation_dogs_dir)

test_cats_dir = os.path.join(test_dir,'real')
os.mkdir(test_cats_dir)
test_dogs_dir = os.path.join(test_dir,'fake')
os.mkdir(test_dogs_dir)

## file 복사 ##
## real 총 개수: 16293 
## fake 총 개수 : 79341 



for fname in list_df_real[0:9000]:
    src = os.path.join(original_dataset_dir,fname)
    dst = os.path.join(train_cats_dir, fname)
    shutil.copyfile(src,dst)


for fname in list_df_real[9000:13500]:
    src = os.path.join(original_dataset_dir,fname)
    dst = os.path.join(validation_cats_dir, fname)
    shutil.copyfile(src,dst)


for fname in list_df_real[13500:16293]:
    src = os.path.join(original_dataset_dir,fname)
    dst = os.path.join(test_cats_dir, fname)
    shutil.copyfile(src,dst)
    

for fname in list_df_fake[0:40000]:
    src = os.path.join(original_dataset_dir,fname)
    dst = os.path.join(train_dogs_dir, fname)
    shutil.copyfile(src,dst)


for fname in list_df_fake[40000:60000]:
    src = os.path.join(original_dataset_dir,fname)
    dst = os.path.join(validation_dogs_dir, fname)
    shutil.copyfile(src,dst)


for fname in list_df_fake[60000:79341]:
    src = os.path.join(original_dataset_dir,fname)
    dst = os.path.join(test_dogs_dir, fname)
    shutil.copyfile(src,dst)